### ISSUE TITLE
Option to disable the mute icon in tab

### ISSUE THREAD

**Issue by tacosuzy** [rogerskeie/autoMutePlus#3]
Hello, I am wondering if there is a way to prevent the mute icon appearing in tabs when mute is enabled. All of the auto mute addons I've tried add the button to tabs making it easy to accidentally click the button disabling mute when a lot of tabs are open. I'm guessing it is on firefox's side but not sure. Do you see a way to make this possible? I have disabled the icon in about:config which works but then the addons undo it.

**Comment by rogerskeie** [comment]
Hi,

I just did a quick Google search, but it seems that this is currently not possible in the WebExtensions API.

One suggestion I found which might work is adding this to your userChrome.css (and restarting your browser):
```javascript
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
.tab-icon-overlay[muted],.tab-icon-sound[muted],.tab-icon-overlay[soundplaying],.tab-icon-sound[soundplaying] {
    display: none !important;
}
```

**Comment by tacosuzy** [comment]
I found an extension that mutes tabs that are not focused without adding the mute icon but once you go to the muted tab it unmutes and stays unmuted even when going back to the non muted. It is called unMute. But it doesn't have a mute all or whitelist. Early stages. Thank you for responding so quickly. I will try that and also message the maker of unMute to inquire.

Does that remove it and disable it or hide it but not disable functionality? I found a css in my searches that hides it visually.

**Comment by rogerskeie** [comment]
The CSS i found only affects visibility.

**Comment by tacosuzy** [comment]
With the CSS you posted, and the about:config browser.tabs.showAudioPlayingIcon set to false the mute icon is visually gone and disabled. Or it moves it out of existence. I am clicking everywhere near the x and the function is absent. Could be a fluke I don't know but thank you for your help.

**Comment by rogerskeie** [comment]
You're welcome, glad I could help.

To manually mute or unmute individual tabs when the speaker icon hidden, you can right click on the tab and click Mute Tab or Unmute Tab, or simply press the "m" key on your keyboard when the tab context menu is open.
